//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaptopShopEntities : DbContext
    {
        public LaptopShopEntities()
            : base("name=LaptopShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Batteries> Batteries { get; set; }
        public virtual DbSet<Bluetooth> Bluetooth { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Chargers> Chargers { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<CPUs> CPUs { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<GPUs> GPUs { get; set; }
        public virtual DbSet<Keyboards> Keyboards { get; set; }
        public virtual DbSet<Orderlines> Orderlines { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PortConnections> PortConnections { get; set; }
        public virtual DbSet<Ports> Ports { get; set; }
        public virtual DbSet<PostalCodes> PostalCodes { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<Screens> Screens { get; set; }
        public virtual DbSet<Speakers> Speakers { get; set; }
        public virtual DbSet<Storages> Storages { get; set; }
        public virtual DbSet<WiFi> WiFi { get; set; }
    }
}
