//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orderlines = new HashSet<Orderlines>();
            this.PortConnections = new HashSet<PortConnections>();
        }
    
        public int ProductId { get; set; }
        public int CPUId { get; set; }
        public int GPUId { get; set; }
        public int RAMId { get; set; }
        public int ColorId { get; set; }
        public int BrandId { get; set; }
        public int StorageId { get; set; }
        public int BatteryId { get; set; }
        public int ScreenId { get; set; }
        public int Weight { get; set; }
        public bool FingerprintScanner { get; set; }
        public int SpeakerId { get; set; }
        public int WiFiId { get; set; }
        public int BluetoothId { get; set; }
        public int KeyboardId { get; set; }
        public bool Microphone { get; set; }
        public bool Webcam { get; set; }
        public string ModelNumber { get; set; }
        public int Price { get; set; }
    
        public virtual Batteries Batteries { get; set; }
        public virtual Bluetooth Bluetooth { get; set; }
        public virtual Brands Brands { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual CPUs CPUs { get; set; }
        public virtual GPUs GPUs { get; set; }
        public virtual Keyboards Keyboards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderlines> Orderlines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortConnections> PortConnections { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual Screens Screens { get; set; }
        public virtual Speakers Speakers { get; set; }
        public virtual Storages Storages { get; set; }
        public virtual WiFi WiFi { get; set; }
    }
}
