//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screens()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ScreenId { get; set; }
        public string Resolution { get; set; }
        public double Size { get; set; }
        public bool HDR { get; set; }
        public int Brightness { get; set; }
        public bool Touch { get; set; }
        public string AspectRatio { get; set; }
        public string ScreenTechnology { get; set; }
        public string SyncType { get; set; }
        public int RefreshRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
